spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/sinji
  jpa:
    properties:
      hibernate:
        default_fetch_size: 100
        show_sql: true
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: create
        database-platform : org.hibernate.dialect.MySQL8Dialect